api_platform:
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ["text/html"]
        mlutipart: ["multipart/form-data"]

    title: 'Symfony Brasil Burger'
    description: 'Application web et mobile.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
