# controllers:
#     resource: ../src/Controller/
#     type: attribute


# authentication_token:
#         path:/api/authentication_token
#         methods: [’POST’]

api_login_check:
    path: /api/login
    
controllers:
    resource: ../src/Controller/
    type: attribute